/**
 * Offline license verification (machine-locked, signed).
 *
 * A license is `base64(payload).base64(signature)` where payload is
 * `{ v, mid, store, iss, exp }` signed with Ed25519 by the private key held only
 * by the vendor (see tools/license-keygen.mjs). The app trusts ONLY signatures
 * from LICENSE_PUBLIC_KEY below, and only for its OWN machine id — so a copied
 * install can't run (its machine id won't match) and nobody can forge a license
 * without the private key.
 *
 * Verification runs in the app (JS). This stops casual copying between shops —
 * the real-world threat — not a determined reverse-engineer; that's an accepted
 * trade-off for an offline app (see docs, if any).
 */

/** Vendor public key (raw Ed25519, base64). Generated by `license-keygen genkeys`. */
export const LICENSE_PUBLIC_KEY = "RpMEiaZA8pdb/6UVteC6YJBREc3xrg9jseGEchmyf2I="

export interface LicensePayload {
  v: number
  /** Machine id the license is bound to. */
  mid: string
  /** Shop / store name (for display). */
  store: string
  /** Issue date YYYY-MM-DD. */
  iss: string
  /** Expiry date YYYY-MM-DD. */
  exp: string
}

export type LicenseReason =
  | "ok"
  | "malformed"
  | "bad-signature"
  | "wrong-machine"
  | "expired"
  | "error"

export interface LicenseResult {
  valid: boolean
  reason: LicenseReason
  store?: string
  exp?: string
  /** Days until expiry (negative if past). Present when the signature is valid. */
  daysLeft?: number
}

const unb64 = (s: string): Uint8Array<ArrayBuffer> => {
  const bin = atob(s)
  const arr = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i)
  return arr
}
const toDay = (d: Date): string => d.toISOString().slice(0, 10)
const daysBetween = (fromDay: string, to: Date): number =>
  Math.floor((Date.parse(fromDay + "T00:00:00Z") - Date.parse(toDay(to) + "T00:00:00Z")) / 86400000)

let cachedKey: CryptoKey | null = null
async function publicKey(): Promise<CryptoKey> {
  if (!cachedKey) {
    cachedKey = await crypto.subtle.importKey("raw", unb64(LICENSE_PUBLIC_KEY), { name: "Ed25519" }, false, ["verify"])
  }
  return cachedKey
}

/**
 * Verify a license string against a machine id. `now` is injectable for testing.
 * Signature is always checked first; machine/expiry only after it's authentic.
 */
export async function verifyLicense(
  license: string,
  machineId: string,
  now: Date = new Date(),
): Promise<LicenseResult> {
  try {
    const [payloadB64, sigB64] = (license ?? "").trim().split(".")
    if (!payloadB64 || !sigB64) return { valid: false, reason: "malformed" }
    const bytes = unb64(payloadB64)
    const sig = unb64(sigB64)
    const ok = await crypto.subtle.verify({ name: "Ed25519" }, await publicKey(), sig, bytes)
    if (!ok) return { valid: false, reason: "bad-signature" }
    const payload = JSON.parse(new TextDecoder().decode(bytes)) as LicensePayload
    const daysLeft = daysBetween(payload.exp, now)
    if (payload.mid !== machineId) return { valid: false, reason: "wrong-machine", store: payload.store, exp: payload.exp, daysLeft }
    if (payload.exp < toDay(now)) return { valid: false, reason: "expired", store: payload.store, exp: payload.exp, daysLeft }
    return { valid: true, reason: "ok", store: payload.store, exp: payload.exp, daysLeft }
  } catch {
    return { valid: false, reason: "error" }
  }
}
